ProjectD/Controllers/AzureDBs1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectD.Data;
using ProjectD.Models;

namespace ProjectD.Controllers
{
    public class AzureDBs1Controller : Controller
    {
        private readonly ApplicationDbContext _context;
        
        public AzureDBs1Controller(ApplicationDbContext context)
        {
            _context = context;    
        }


        // GET: AzureDBs1
        public async Task<IActionResult> Index()
        {
            return View(await _context.Marketinfo_shop.ToListAsync());
        }

        // GET: AzureDBs1/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var azureDB = await _context.Marketinfo_shop
                .SingleOrDefaultAsync(m => m.縣市 == id);
            if (azureDB == null)
            {
                return NotFound();
            }

            return View(azureDB);
        }

        // GET: AzureDBs1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AzureDBs1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("縣市,市集名稱,市集介紹,營業時間,電話,GPS,營業地址,交通資訊")] AzureDB azureDB)
        {
            if (ModelState.IsValid)
            {
                _context.Add(azureDB);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(azureDB);
        }

        // GET: AzureDBs1/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
        
            var azureDB = await _context.Marketinfo_shop.SingleOrDefaultAsync(m => m.縣市 == id);
            if (azureDB == null)
            {
                return NotFound();
            }
            return View(azureDB);
        }

        // POST: AzureDBs1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("縣市,市集名稱,市集介紹,營業時間,電話,GPS,營業地址,交通資訊")] AzureDB azureDB)
        {
            if (id != azureDB.縣市)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(azureDB);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AzureDBExists(azureDB.縣市))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(azureDB);
        }

        // GET: AzureDBs1/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var azureDB = await _context.Marketinfo_shop
                .SingleOrDefaultAsync(m => m.縣市 == id);
 

            if (azureDB == null)
            {
                return NotFound();
            }
            
            return View(azureDB);
        }

        // POST: AzureDBs1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var azureDB = await _context.Marketinfo_shop.SingleOrDefaultAsync(m => m.縣市 == id);
            _context.Marketinfo_shop.Remove(azureDB);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool AzureDBExists(string id)
        {
            return _context.Marketinfo_shop.Any(e => e.縣市 == id);
        }
    }
}

ProjectD/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> i農管家: )</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/carousel.css" runat="server" />
        <link rel="stylesheet" href="~/css/site.css" runat="server" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"   runat="server"/>
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<!--
<body>
    <div class="navbar-wrapper">
        <div class="container">

            <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">i農管家</a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-area="" asp-controller="Home" asp-action="iMap">iMap</a></li>
                            <li><a asp-area="" asp-controller="Home" asp-action="iShop">iShop</a></li>
                            <li><a asp-area="" asp-controller="AzureDBs1" asp-action="Index">DBTest</a></li>
                        </ul>

                    </div>
                </div>
            </nav>

        </div>
    </div>
-->
<body>
    <div class="navbar-wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <form class="navbar-brand">
                            <b ><font color="White" size="10">i農管家</font></b>
                            <br />
                            <b ><font color="White" size="2">不只用心，更貼近你心</font></b>
                    </form>
                     
                    
</div>
                <div class="navbar-collapse collapse navbar-collapse-center">
                    <ul class="nav navbar-nav navbar-center">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a href="#aaa">關於i農管家</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="iMap" >i農地圖</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Client_Template">iShop</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="iShop">test</a></li>
                    </ul>
                  <!-- @await Html.PartialAsync("_LoginPartial")-->
                       <!--<li><a asp-area="" asp-controller="Home" asp-action="iShop">iShop</a></li>
                        <li><a asp-area="" asp-controller="AzureDBs1" asp-action="Index">DBTest</a></li>-->
                </div>
            </div>
        </nav>
</div>
</body>
        @RenderBody()
        <hr />

<div id="footerwrap">
    <div class="container">
        <div class="row-centered">
            <div class="col-lg-4">
                <p><b>2017 - Project Demeter present</b></p>
            </div>

            <div class="col-lg-4">
                <p><b>Living in the amazing Taiwan.</b></p>
            </div>
        </div>
    </div>
</div> 

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    </body>
</html>